'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { MapPin, Pencil, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';

import { Badge, ConfirmDialog, StatusState, ToastBar, useToastSimple } from '@/components/company/company-shared';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Spinner } from '@/components/ui/spinner';
import { ApiError } from '@/lib/api-client';
import { getCountries } from '@/lib/auth/api';
import type { CountryResponse } from '@/lib/auth/types';
import { useAuthStore } from '@/lib/auth/store';
import { createCity, deleteCity, getCities, updateCity } from '@/lib/company/api';
import type { CityRequest, CityResponse } from '@/lib/company/types';
import { useTranslation } from '@/lib/i18n';

type CityForm = { cityName: string; countryId: string };
const toForm = (city?: CityResponse): CityForm => ({ cityName: city?.cityName ?? '', countryId: city ? String(city.countryId) : '' });

function CityDialog({ city, countries, open, loading, error, onClose, onSave }: { city: CityResponse | null; countries: CountryResponse[]; open: boolean; loading: boolean; error: string | null; onClose: () => void; onSave: (form: CityForm) => void }) {
  const { t } = useTranslation('dashboard'); const [form, setForm] = useState<CityForm>(toForm(city ?? undefined));
  useEffect(() => { if (open) setForm(toForm(city ?? undefined)); }, [city, open]);
  return <Dialog open={open} onOpenChange={(next) => !next && !loading && onClose()}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>{city ? t('citiesManagement.dialog.editTitle') : t('citiesManagement.dialog.createTitle')}</DialogTitle></DialogHeader><div className="space-y-4 py-2"><div className="space-y-2"><Label htmlFor="city-name">{t('citiesManagement.dialog.name')}</Label><Input id="city-name" value={form.cityName} onChange={(event) => setForm((current) => ({ ...current, cityName: event.target.value }))} placeholder={t('citiesManagement.dialog.namePlaceholder')} maxLength={120} autoFocus /></div><div className="space-y-2"><Label htmlFor="city-country">{t('citiesManagement.dialog.country')}</Label><select id="city-country" value={form.countryId} onChange={(event) => setForm((current) => ({ ...current, countryId: event.target.value }))} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">{t('citiesManagement.dialog.selectCountry')}</option>{countries.map((country) => <option key={country.countryId} value={country.countryId}>{country.countryName}</option>)}</select></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={onClose} disabled={loading}>{t('common.cancel')}</Button><Button onClick={() => onSave(form)} disabled={loading || !form.cityName.trim() || !form.countryId}>{loading ? t('common.saving') : t('citiesManagement.dialog.save')}</Button></DialogFooter></DialogContent></Dialog>;
}

export function CitiesManagement() {
  const token = useAuthStore((state) => state.token); const authRole = useAuthStore((state) => state.role); const { t } = useTranslation('dashboard'); const { toast, success, error: showError } = useToastSimple();
  const [cities, setCities] = useState<CityResponse[]>([]); const [countries, setCountries] = useState<CountryResponse[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState<string | null>(null); const [query, setQuery] = useState(''); const [editor, setEditor] = useState<CityResponse | null | undefined>(undefined); const [deleteTarget, setDeleteTarget] = useState<CityResponse | null>(null); const [submitting, setSubmitting] = useState(false); const [dialogError, setDialogError] = useState<string | null>(null);
  const canDelete = authRole === 'SUPER_ADMIN';
  const refresh = useCallback(async () => { setLoading(true); setLoadError(null); try { const [nextCities, nextCountries] = await Promise.all([getCities(), getCountries()]); setCities(nextCities); setCountries(nextCountries); } catch (error) { setLoadError(error instanceof ApiError ? error.message : t('citiesManagement.errors.load')); } finally { setLoading(false); } }, [t]);
  useEffect(() => { void refresh(); }, [refresh]);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return [...cities].filter((city) => !needle || `${city.cityName} ${city.countryName}`.toLowerCase().includes(needle)).sort((a, b) => a.cityName.localeCompare(b.cityName)); }, [cities, query]);
  const save = async (form: CityForm) => { if (!token) return; setSubmitting(true); setDialogError(null); const payload: CityRequest = { cityName: form.cityName.trim(), countryId: Number(form.countryId) }; try { const updated = editor ? await updateCity(token, editor.cityId, payload) : await createCity(token, payload); setCities((current) => editor ? current.map((city) => city.cityId === updated.cityId ? updated : city) : [...current, updated]); success(t(editor ? 'citiesManagement.messages.updated' : 'citiesManagement.messages.created')); setEditor(undefined); } catch (error) { setDialogError(error instanceof ApiError ? error.message : t('citiesManagement.errors.save')); } finally { setSubmitting(false); } };
  const remove = async () => { if (!token || !deleteTarget || !canDelete) return; setSubmitting(true); try { await deleteCity(token, deleteTarget.cityId); setCities((current) => current.filter((city) => city.cityId !== deleteTarget.cityId)); success(t('citiesManagement.messages.deleted')); setDeleteTarget(null); } catch (error) { showError(error instanceof ApiError ? error.message : t('citiesManagement.errors.delete')); } finally { setSubmitting(false); } };
  return <div className="space-y-5 pb-20 md:pb-0"><ToastBar toast={toast} /><CityDialog city={editor ?? null} countries={countries} open={editor !== undefined} loading={submitting} error={dialogError} onClose={() => { setEditor(undefined); setDialogError(null); }} onSave={save} /><ConfirmDialog open={Boolean(deleteTarget)} title={t('citiesManagement.deleteTitle')} description={t('citiesManagement.deleteDescription')} confirmLabel={t('citiesManagement.delete')} destructive loading={submitting} onConfirm={remove} onCancel={() => setDeleteTarget(null)} /><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-xl font-bold text-foreground sm:text-2xl">{t('citiesManagement.title')}</h1><p className="mt-1 text-sm text-muted-foreground">{t('citiesManagement.subtitle')}</p></div><Button className="gap-2" onClick={() => { setDialogError(null); setEditor(null); }}><Plus className="h-4 w-4" />{t('citiesManagement.add')}</Button></div><div className="relative max-w-xl"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('citiesManagement.search')} className="pl-9" /></div>{loading ? <div className="flex justify-center py-24"><Spinner className="h-8 w-8 text-primary" /></div> : loadError ? <StatusState icon={MapPin} tone="destructive" title={t('common.loadError')} description={loadError} action={<Button variant="outline" onClick={refresh} className="gap-2"><RefreshCw className="h-4 w-4" />{t('common.retry')}</Button>} /> : filtered.length === 0 ? <StatusState icon={MapPin} title={cities.length ? t('common.noResults') : t('citiesManagement.emptyTitle')} description={cities.length ? t('common.tryAnotherSearch') : t('citiesManagement.emptyDescription')} /> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((city) => <Card key={city.cityId}><CardContent className="flex gap-3 p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary"><MapPin className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-semibold text-foreground">{city.cityName}</p><Badge className="mt-1 bg-muted text-muted-foreground">{city.countryName}</Badge><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" className="gap-1" onClick={() => { setDialogError(null); setEditor(city); }}><Pencil className="h-3.5 w-3.5" />{t('citiesManagement.edit')}</Button>{canDelete && <Button size="sm" variant="outline" className="gap-1 text-destructive hover:text-destructive" onClick={() => setDeleteTarget(city)}><Trash2 className="h-3.5 w-3.5" />{t('citiesManagement.delete')}</Button>}</div>{!canDelete && <p className="mt-3 text-xs text-muted-foreground">{t('citiesManagement.restrictedDelete')}</p>}</div></CardContent></Card>)}</div>}</div>;
}
